# Generated by Django 2.0.2 on 2018-03-02 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='UserDataModel2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('av', models.CharField(max_length=200)),
                ('an', models.CharField(max_length=200)),
                ('ec', models.CharField(max_length=200)),
                ('rsd', models.CharField(max_length=200)),
                ('scsd', models.CharField(max_length=200)),
                ('ecd', models.CharField(max_length=200)),
                ('nt', models.CharField(max_length=200)),
                ('rft', models.CharField(max_length=200)),
                ('i10', models.CharField(max_length=200)),
                ('sced', models.CharField(max_length=200)),
                ('iuf', models.CharField(max_length=200)),
                ('red', models.CharField(max_length=200)),
                ('fsd', models.CharField(max_length=200)),
                ('spsd', models.CharField(max_length=200)),
                ('dlsd', models.CharField(max_length=200)),
                ('sped', models.CharField(max_length=200)),
                ('dz', models.CharField(max_length=200)),
                ('pi', models.CharField(max_length=200)),
                ('rt', models.CharField(max_length=200)),
                ('rc', models.CharField(max_length=200)),
                ('dled', models.CharField(max_length=200)),
                ('csd', models.CharField(max_length=200)),
                ('re', models.CharField(max_length=200)),
                ('at', models.CharField(max_length=200)),
                ('npn', models.CharField(max_length=200)),
                ('pc', models.CharField(max_length=200)),
                ('ced', models.CharField(max_length=200)),
                ('cp', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lo', models.CharField(max_length=200)),
                ('prov', models.CharField(max_length=200)),
                ('dt', models.CharField(max_length=200)),
                ('tec', models.CharField(max_length=200)),
                ('ct', models.CharField(max_length=200)),
                ('ui', models.CharField(max_length=200)),
                ('ns', models.CharField(max_length=200)),
                ('ver', models.CharField(max_length=200)),
                ('ot', models.CharField(max_length=200)),
                ('mn', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='userdatamodel2',
            name='usermodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start.UserModel2'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start.Question'),
        ),
    ]
