# Generated by Django 2.0.2 on 2018-03-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdatamodel2',
            name='an',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userdatamodel2',
            name='at',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userdatamodel2',
            name='av',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userdatamodel2',
            name='ced',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userdatamodel2',
            name='cp',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userdatamodel2',
            name='csd',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userdatamodel2',
            name='dled',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userdatamodel2',
            name='dlsd',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userdatamodel2',
            name='dz',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userdatamodel2',
            name='ec',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userdatamodel2',
            name='ecd',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userdatamodel2',
            name='fsd',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userdatamodel2',
            name='i10',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userdatamodel2',
            name='iuf',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userdatamodel2',
            name='npn',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userdatamodel2',
            name='nt',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userdatamodel2',
            name='pc',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userdatamodel2',
            name='pi',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userdatamodel2',
            name='rc',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userdatamodel2',
            name='re',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userdatamodel2',
            name='red',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userdatamodel2',
            name='rft',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userdatamodel2',
            name='rsd',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userdatamodel2',
            name='rt',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userdatamodel2',
            name='sced',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userdatamodel2',
            name='scsd',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userdatamodel2',
            name='sped',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userdatamodel2',
            name='spsd',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
