# Generated by Django 2.0.2 on 2018-03-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0002_auto_20180313_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='usermodel2',
            name='ct',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='usermodel2',
            name='dt',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='usermodel2',
            name='lo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='usermodel2',
            name='mn',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='usermodel2',
            name='ns',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='usermodel2',
            name='ot',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='usermodel2',
            name='prov',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='usermodel2',
            name='tec',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='usermodel2',
            name='ui',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='usermodel2',
            name='ver',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
