# Generated by Django 2.0.2 on 2018-03-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0003_auto_20180313_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel2',
            name='la',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
