# Generated by Django 2.0.2 on 2018-03-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0004_usermodel2_la'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdatamodel2',
            name='at',
        ),
        migrations.RemoveField(
            model_name='userdatamodel2',
            name='dled',
        ),
        migrations.RemoveField(
            model_name='userdatamodel2',
            name='iuf',
        ),
        migrations.RemoveField(
            model_name='userdatamodel2',
            name='nt',
        ),
        migrations.RemoveField(
            model_name='userdatamodel2',
            name='re',
        ),
        migrations.RemoveField(
            model_name='userdatamodel2',
            name='sped',
        ),
        migrations.RemoveField(
            model_name='userdatamodel2',
            name='spsd',
        ),
        migrations.AddField(
            model_name='userdatamodel2',
            name='rped',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userdatamodel2',
            name='rpsd',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userdatamodel2',
            name='ced',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userdatamodel2',
            name='csd',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userdatamodel2',
            name='dlsd',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userdatamodel2',
            name='ecd',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userdatamodel2',
            name='fsd',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userdatamodel2',
            name='i10',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userdatamodel2',
            name='npn',
            field=models.CharField(default='', max_length=19),
        ),
        migrations.AlterField(
            model_name='userdatamodel2',
            name='pc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userdatamodel2',
            name='rc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userdatamodel2',
            name='red',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userdatamodel2',
            name='rft',
            field=models.CharField(default='', max_length=19),
        ),
        migrations.AlterField(
            model_name='userdatamodel2',
            name='rsd',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userdatamodel2',
            name='sced',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userdatamodel2',
            name='scsd',
            field=models.FloatField(default=0),
        ),
    ]
