# Generated by Django 2.0.2 on 2018-03-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0005_auto_20180319_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdatamodel2',
            name='dled',
            field=models.FloatField(default=0),
        ),
    ]
